### ISSUE TITLE
Astar seems to be Hosted by Blockscout, not SelfHosted.

### ISSUE THREAD

**Issue by jaripy** [blockscout/docs-archive#106]
[Here ](https://docs.blockscout.com/about/projects#polkadot-ecosystem)in Docs, Astar is SelfHosted, but I think it is Hosted by Blockscout as far as I jump to the [Astar link](https://blockscout.com/astar).
It does not appear to be SelfHosted because the Astar link is `https://blockscout.com/astar`.

**Comment by andogro** [comment]
added to chains page
