### ISSUE TITLE
Typo of Bitkub and more update

### ISSUE THREAD

**Issue by kongrath** [blockscout/docs-archive#226]
In file projects.md at table A-F [here](https://docs.blockscout.com/about/projects#a-f), could please change the name of our chain from

Bitcub => Bitkub

and update on the description  from

"Proof of Staked Authority (PoSA) chain serving the Thai community." => "Proof of Stake (PoS) chain serving the Thai community."

Thanks

**Comment by andogro** [comment]
No longer relevant
