### ISSUE TITLE
websocket url of kotti network

### ISSUE THREAD

**Issue by racetrack0616** [blockscout/docs-archive#26]
What is websocket url of kotti network in blockscout explorer?

**Comment by vbaranov** [comment]
POA team do not host Kotti Blockscout instance anymore. https://docs.blockscout.com/about/use-cases/hosted-blockscout

> * Ethereum Classic (ETC) is hosted by the ETC Cooperative. We run a proxy to maintain the current blockscout based-url. ETC Cooperative also hosts the Kotti and Mordor testnets

You should ask ETC Cooperative regarding Kotti/Mordor/ETC instances https://etccooperative.org/contact

**Comment by racetrack0616** [comment]
Nobody in the contact list is interested in answering queries. Such a poor community and support level. :(
