### ISSUE TITLE
Not able to swap or send solana and solana coins

### ISSUE THREAD

**Issue by Gagan677** [blockscout/docs-archive#343]

**Comment by Gordonhills** [comment]
Hello @Gagan677 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID SOL07638
Please see the link below to our dedicated support line:
[Solana Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
