### ISSUE TITLE
Documentation to run tests seems outdated

### ISSUE THREAD

**Issue by SebastienGllmt** [blockscout/docs-archive#48]
*Describe your issue here.*

The test documentation seems to be out of date 

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):  Elixir 1.12.3 (compiled with Erlang/OTP 24)
* Operating System: WSL2
* Blockscout Version/branch:  master / b05c5c6ed2398cf21decc15a715b17f20d5aa428

### Steps to reproduce

The [current testing documentation](https://docs.blockscout.com/for-developers/testing) says to run `mix coveralls.html --umbrella`

However, this fails because it seems coveralls was [previously removed](https://github.com/blockscout/blockscout/pull/3761)

### Expected behaviour

Tests run successfully

### Actual behaviour

```
** (Mix) The task "coveralls.html" could not be found
```

### Additional note

Okay, so far I've found that you have to do the following:

1. sudo -u postgres dropdb explorer_test
2. sudo -u postgres createdb explorer_test
3. sudo -u postgres createuser blockscout_test
4. sudo -u postgres psql
5. \password blockscout_test
6. ALTER USER blockscout_test WITH SUPERUSER;
7. grant all privileges on database explorer_test to blockscout_test ;
8. Set the env variables as follows (note: db name/username/password match what you set in the previous step)
```sh
# note: remember to set MIX_ENV=prod when you want to go back to running production builds
export MIX_ENV=test
export PGUSER=blockscout_test
export PGPASSWORD=blockscouttestpassword
export ETHEREUM_JSONRPC_CASE=EthereumJSONRPC.Case.Parity.Mox
export ETHEREUM_JSONRPC_WEB_SOCKET_CASE=EthereumJSONRPC.WebSocket.Case.Mox
export CHAIN_ID=77
export ADMIN_PANEL_ENABLED=true
```
9. Install chromedriver. You can reference the script at `./bin/install_chrome_headless.sh` for how to do it, but note that the **chromedriver version much match your chrome version** (notably, open chrome and find the first 3 parts of your version number such as x.x.xxxx)
10. mix test --no-start --exclude no_parity (you can also run a specific test using `mix cmd --app block_scout_web mix test test/block_scout_web/schema/query/address_test.exs`)

#### Possibly missing step

I ran into a weird issue that was resolved by restarting my machine. Possibly this is a required step somewhere (I explicitly remember just restarting the postgres service didn't fix it). Here is the constraint issue resolved by restarting my machine is below in case this sounds familiar and there is a better step for the docs to resolve this

```
     ** (Ecto.ConstraintError) constraint error when attempting to insert struct:

         * one_consensus_block_at_height (unique_constraint)

     If you would like to stop this constraint violation from raising an
     exception and instead add it as an error to your changeset, please
     call `unique_constraint/3` on your changeset with the constraint
     `:name` as an option.

     The changeset has not defined any constraint.
```

**Comment by vbaranov** [comment]
@SebastienGllmt Thank you. Documentation updated https://docs.blockscout.com/for-developers/testing
