### ISSUE TITLE
Blockscout ecosystem diagram

### ISSUE THREAD

**Issue by tgladilina** [blockscout/docs-archive#83]
can you add to your queue creation of a Blockscout ecosystem diagram? Would feature all of the instances grouped by chain environment  on the projects page (ie Ethereum, Polygon, Optimism, Rollups, etc).

![Image](https://user-images.githubusercontent.com/103045386/195903195-89a03f36-3367-4121-bb76-f1ff6af1b3a9.png)

![Image](https://user-images.githubusercontent.com/103045386/195903226-f331dcc7-b1d3-4a58-b741-2f8c25b06da1.png)

![Image](https://user-images.githubusercontent.com/103045386/201534391-eb7c40a4-4b3c-4203-8853-fa0ca5c116af.png)

![Image](https://user-images.githubusercontent.com/103045386/201534419-4ec3d580-79a3-427d-a6c8-598247f86e84.png)

**Comment by tgladilina** [comment]
@andogro please review 

v1
![Image](https://user-images.githubusercontent.com/103045386/202200914-a1c2ab60-6084-4e6f-b34f-2402a1c5df88.png)
 
v2
![Image](https://user-images.githubusercontent.com/103045386/202204469-ba06ca08-6003-444c-ad92-5ca4f13887f3.png)

**Comment by andogro** [comment]
old issue
