### ISSUE TITLE
Media kit

### ISSUE THREAD

**Issue by tgladilina** [blockscout/docs-archive#84]
Logos pack 

![Image](https://user-images.githubusercontent.com/103045386/195903649-bbc222f4-18b5-44b8-a6e5-308379ff2c4b.png)

**Comment by tgladilina** [comment]
Media Kit (SVG and PNG formats)

[Blockscout_media_kit.zip](https://github.com/blockscout/docs/files/9788629/Blockscout_media_kit.zip)

**Comment by andogro** [comment]
on docs site
